// class FoodRecipeModel {
//   int? id;
//   String? title;
//   String? image;
//   String? imageType;
//   int? calories;
//   String? protein;
//   String? fat;
//   String? carbs;

//   FoodRecipeModel(
//       {this.id,
//       this.title,
//       this.image,
//       this.imageType,
//       this.calories,
//       this.protein,
//       this.fat,
//       this.carbs});

//   FoodRecipeModel.fromJson(Map<dynamic, dynamic> json) {
//     id = json['id'];
//     title = json['title'];
//     image = json['image'];
//     imageType = json['imageType'];
//     calories = json['calories'];
//     protein = json['protein'];
//     fat = json['fat'];
//     carbs = json['carbs'];
//   }

//   Map<dynamic, dynamic> toJson() {
//     final Map<dynamic, dynamic> data = new Map<dynamic, dynamic>();
//     data['id'] = this.id;
//     data['title'] = this.title;
//     data['image'] = this.image;
//     data['imageType'] = this.imageType;
//     data['calories'] = this.calories;
//     data['protein'] = this.protein;
//     data['fat'] = this.fat;
//     data['carbs'] = this.carbs;
//     return data;
//   }
// }



// by ingredient
class Autogenerated {
  int? id;
  String? title;
  String? image;
  String? imageType;
  int? usedIngredientCount;
  int? missedIngredientCount;
  List<MissedIngredients>? missedIngredients;
  List<UsedIngredients>? usedIngredients;
  List<Null>? unusedIngredients;
  int? likes;

  Autogenerated(
      {this.id,
      this.title,
      this.image,
      this.imageType,
      this.usedIngredientCount,
      this.missedIngredientCount,
      this.missedIngredients,
      this.usedIngredients,
      this.unusedIngredients,
      this.likes});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    image = json['image'];
    imageType = json['imageType'];
    usedIngredientCount = json['usedIngredientCount'];
    missedIngredientCount = json['missedIngredientCount'];
    if (json['missedIngredients'] != null) {
      missedIngredients = <MissedIngredients>[];
      json['missedIngredients'].forEach((v) {
        missedIngredients!.add(new MissedIngredients.fromJson(v));
      });
    }
    if (json['usedIngredients'] != null) {
      usedIngredients = <UsedIngredients>[];
      json['usedIngredients'].forEach((v) {
        usedIngredients!.add(new UsedIngredients.fromJson(v));
      });
    }
    if (json['unusedIngredients'] != null) {
      unusedIngredients = <Null>[];
      json['unusedIngredients'].forEach((v) {
        unusedIngredients!.add(new Null.fromJson(v));
      });
    }
    likes = json['likes'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    data['image'] = this.image;
    data['imageType'] = this.imageType;
    data['usedIngredientCount'] = this.usedIngredientCount;
    data['missedIngredientCount'] = this.missedIngredientCount;
    if (this.missedIngredients != null) {
      data['missedIngredients'] =
          this.missedIngredients!.map((v) => v.toJson()).toList();
    }
    if (this.usedIngredients != null) {
      data['usedIngredients'] =
          this.usedIngredients!.map((v) => v.toJson()).toList();
    }
    if (this.unusedIngredients != null) {
      data['unusedIngredients'] =
          this.unusedIngredients!.map((v) => v.toJson()).toList();
    }
    data['likes'] = this.likes;
    return data;
  }
}

class MissedIngredients {
  int? id;
  double? amount;
  String? unit;
  String? unitLong;
  String? unitShort;
  String? aisle;
  String? name;
  String? original;
  String? originalName;
  List<String>? meta;
  String? extendedName;
  String? image;

  MissedIngredients(
      {this.id,
      this.amount,
      this.unit,
      this.unitLong,
      this.unitShort,
      this.aisle,
      this.name,
      this.original,
      this.originalName,
      this.meta,
      this.extendedName,
      this.image});

  MissedIngredients.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    amount = json['amount'];
    unit = json['unit'];
    unitLong = json['unitLong'];
    unitShort = json['unitShort'];
    aisle = json['aisle'];
    name = json['name'];
    original = json['original'];
    originalName = json['originalName'];
    meta = json['meta'].cast<String>();
    extendedName = json['extendedName'];
    image = json['image'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['amount'] = this.amount;
    data['unit'] = this.unit;
    data['unitLong'] = this.unitLong;
    data['unitShort'] = this.unitShort;
    data['aisle'] = this.aisle;
    data['name'] = this.name;
    data['original'] = this.original;
    data['originalName'] = this.originalName;
    data['meta'] = this.meta;
    data['extendedName'] = this.extendedName;
    data['image'] = this.image;
    return data;
  }
}

class UsedIngredients {
  int? id;
  int? amount;
  String? unit;
  String? unitLong;
  String? unitShort;
  String? aisle;
  String? name;
  String? original;
  String? originalName;
  List<String>? meta;
  String? image;

  UsedIngredients(
      {this.id,
      this.amount,
      this.unit,
      this.unitLong,
      this.unitShort,
      this.aisle,
      this.name,
      this.original,
      this.originalName,
      this.meta,
      this.image});

  UsedIngredients.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    amount = json['amount'];
    unit = json['unit'];
    unitLong = json['unitLong'];
    unitShort = json['unitShort'];
    aisle = json['aisle'];
    name = json['name'];
    original = json['original'];
    originalName = json['originalName'];
    meta = json['meta'].cast<String>();
    image = json['image'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['amount'] = this.amount;
    data['unit'] = this.unit;
    data['unitLong'] = this.unitLong;
    data['unitShort'] = this.unitShort;
    data['aisle'] = this.aisle;
    data['name'] = this.name;
    data['original'] = this.original;
    data['originalName'] = this.originalName;
    data['meta'] = this.meta;
    data['image'] = this.image;
    return data;
  }
}

